# Generated by Django 2.2.7 on 2019-11-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('type', models.CharField(max_length=6)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('box_id', models.CharField(max_length=20)),
                ('posX', models.FloatField()),
                ('posY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImagineCode.Box')),
            ],
        ),
    ]
