# Generated by Django 2.2.7 on 2019-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagineCode', '0003_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='posX',
        ),
        migrations.RemoveField(
            model_name='box',
            name='posY',
        ),
        migrations.AddField(
            model_name='box',
            name='pos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
